repos:
  - repo: https://github.com/USA-RedDragon/configulator-rs
    rev: v0.3.0
    hooks:
      - id: configulator-sample
        args: [--type, AppConfig, --sample-file, config.example.yaml]
      - id: configulator-markdown
        args: [--type, AppConfig, --markdown-file, README.md, --env-prefix, MQTT_WX__, --env-separator, __]
