# Sample configuration for AppConfig.
mqtt:
  # MQTT broker hostname
  host: "localhost"
  # MQTT broker port
  port: 1883
  # MQTT username
  username: ""
  # MQTT password
  password: ""
input-topic:
  # Input topic for weather station data
  weather: "weather"
  # Input topic for indoor sensor data
  indoor: "indoor"
  # Input topic for lightning data
  lightning: "lightning"
  # Input topic for light data
  light: "light"
  # Input topic for pressure data
  pressure: "pressure"
  # Input topic for particle sensor data
  particle-sensor: "particle_sensor"
  # Input topic for CO2 sensor data
  co2: "co2"
# Output topic for processed data
output-topic: "processed"
# Sensor height above ground in meters
sensor-height-m: 2.7432
# Field elevation in meters above sea level
elevation-m: 363.2
